spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/board
    username: pibber  # TODO 환경변수로 아이디와 비밀번호를 적용하니 테스트에서 hibernate.dialect 오류 발생
    password: wjsansrk
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always
